from typing import List, Optional
from pydantic import BaseModel
from datetime import datetime

# Patient Schemas
class PatientBase(BaseModel):
    full_name: str
    gender: str
    phone: str
    age: int
    avatar: Optional[str] = None
    level: Optional[str] = "Standard"
    notes: Optional[str] = None

class PatientCreate(PatientBase):
    pass

class Patient(PatientBase):
    id: int
    total_consumption: float
    last_visit_at: Optional[datetime]
    created_at: datetime
    
    class Config:
        orm_mode = True

# Face Exam Schemas
class FaceExamBase(BaseModel):
    image_url: str
    thumbnail_url: Optional[str] = None

class FaceExamCreate(FaceExamBase):
    patient_id: int
    # metrics, advice can be passed or generated by backend

class FaceExam(FaceExamBase):
    id: int
    patient_id: int
    image_hash: Optional[str] = None
    image_width: Optional[int] = None
    image_height: Optional[int] = None
    status: Optional[str] = "done"
    metrics: dict
    advice_summary: str
    detailed_advice: Optional[str]
    ai_provider: Optional[str]
    doctor_confirmed: bool = False
    doctor_notes: Optional[str] = None
    doctor_confirmed_at: Optional[datetime] = None
    created_at: datetime
    
    class Config:
        orm_mode = True

